### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by PHILLIPS71** [Cra5um/node-minecraft-pinger#1]
When ever you ping a server, you get multiple UnhandledPromiseRejectionWarning occurring, before the data retrieved.

`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: cb is not a function`

**Comment by Cra5um** [comment]
I'm sorry but i can't reproduce this bug. Could you show me the code you were using please?

**Comment by PHILLIPS71** [comment]
I've reproduced the bug here

https://runkit.com/59378832eb40190012a026b2/5938923b1a08260012fa6ea0
